### PR TITLE
Plotting

### PR DESCRIPTION
**Pull request by matthiasfabry**
basic plotting. Will be useful to anyone devving

### CODE REVIEW

**Review by matthiasfabry — COMMENTED** [review]
I feel we now have a broad enough base to bring this into main. 
We can make: HRD, and any profile/history plot on two y-axes. 
In principle these templates could be used to create any other line plot.

Kippenhahn remains to be designed later.

**Comment by orlox** [comment]
Remaining annoying issue is fixing CI then? Cause it fails even with live-plotting disabled, right?

**Comment by matthiasfabry** [comment]
Yes, I presume this is compiling related.

**Comment by orlox** [comment]
I can give the github action fix a try now, will push to this same branch. Can you fix the conflict with NuclearBurning.jl in the meantime @matthiasfabry ?

**Comment by orlox** [comment]
@matthiasfabry , never mind, just fixed the conflict. @reinhold-willcox , let's see how much I suffer to try and make CI work :)

**Comment by orlox** [comment]
@reinhold-willcox , if you want to keep playing with this, this one fails a bit further ahead of your trial PR. Current issue is at docdeploy, I don't understand very well how to use the prefix symbol to specify all the things we need.

**Comment by orlox** [comment]
So things seem to work right now IF we have `do_plotting=false`. For some reason if we have `do_plotting=true` the action throws an error saying one of the plotting methods is undefined:

https://github.com/orlox/Jems.jl/actions/runs/6949446092

Would be good to have the doc running with the live plotting at the same time just to be sure it is minimally tested.

It would also be great if one could define ranges for the layout, say
```
          window_specs = ["HR", "profile", "history"]
          window_layouts = [[1:2, 1:2],  # arrangement of plots
                            [1, 3],
                            [2, 3]
                            ]
```
which would create a 2x2 HR diagram with two smaller plots next to it. Makie can take this notation as far as I know, but we can't write it just like that in the toml file because it is not valid. Anyhow that falls into wishlisting.

Anyhow, feel free to squash and merge.

**Comment by matthiasfabry** [comment]
This isn't entirely surprising as `set_window_config` explicitly talks to the windowing system. However if we can trick the server to install GLMakie, it's strange it cannot find the function.

**Comment by matthiasfabry** [comment]
Without this call, the CI succeeds. T
hat being said, I'm still more of a fan to keep plotting off by default on the docs test.

**Comment by orlox** [comment]
Yeah, bizarre...

Let's keep it off then, though we'll need at some point a solution for testing.

**Pull request merged**
